"""Add durable authority, application snapshots and explicit schedule commitments."""
from alembic import op
import sqlalchemy as sa
from app.utils.time import UTCDateTime, utc_now

revision = "20260915_0037"
down_revision = "20260802_0036"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('agent_actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('human', 'agent', 'system')", name='ck_principals_kind'),
    sa.ForeignKeyConstraint(['agent_actor_id'], ['agent_actors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_actor_id')
    )
    op.create_table('identity_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_identity_subject')
    )
    op.create_index(op.f('ix_identity_subjects_principal_id'), 'identity_subjects', ['principal_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'operator', 'member')", name='ck_workspace_memberships_role'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_table('workspace_authority_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bootstrap_principal_id', sa.Integer(), nullable=True),
    sa.Column('operator_principal_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_workspace_authority_singleton'),
    sa.ForeignKeyConstraint(['bootstrap_principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memberships',
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'executor', 'reviewer', 'manager')", name='ck_project_memberships_role'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id', 'project_id')
    )
    op.create_table('principal_profile_links',
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('linked_by_principal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_by_principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['team_member_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('principal_id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('oidc_login_attempts',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('browser_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('verifier', sa.String(length=128), nullable=False),
    sa.Column('return_path', sa.String(length=512), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.Column('consumed_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_index(op.f('ix_oidc_login_attempts_expires_at'), 'oidc_login_attempts', ['expires_at'], unique=False)
    op.create_table('ownership_transfers',
    sa.Column('guest_session_id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('authorized_by_principal_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('transferred_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guest_session_id'], ['user_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('guest_session_id')
    )
    op.create_table('command_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_audit_created_at'), 'command_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_command_audit_principal_id'), 'command_audit', ['principal_id'], unique=False)
    op.create_index(op.f('ix_command_audit_project_id'), 'command_audit', ['project_id'], unique=False)
    op.create_table('application_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('created_by_principal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iteration_id', 'filename', name='uq_application_snapshot_filename')
    )
    op.create_index(op.f('ix_application_snapshots_created_at'), 'application_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_snapshots_iteration_id'), 'application_snapshots', ['iteration_id'], unique=False)
    op.create_table('legacy_snapshot_imports',
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('imported_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checksum')
    )
    op.create_index(op.f('ix_legacy_snapshot_imports_iteration_id'), 'legacy_snapshot_imports', ['iteration_id'], unique=False)
    op.create_table('task_schedule_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'revision', name='uq_task_schedule_baseline_revision')
    )
    op.create_index(op.f('ix_task_schedule_baselines_task_id'), 'task_schedule_baselines', ['task_id'], unique=False)
    op.execute(sa.text("ALTER TABLE user_sessions ADD COLUMN principal_id INTEGER REFERENCES principals(id) ON DELETE RESTRICT"))
    with op.batch_alter_table('user_sessions', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('csrf_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('authenticated_at', UTCDateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_sessions_principal_id'), ['principal_id'], unique=False)

    op.execute(sa.text("ALTER TABLE saved_views ADD COLUMN owner_principal_id INTEGER REFERENCES principals(id) ON DELETE RESTRICT"))
    with op.batch_alter_table('saved_views', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('metric_migration_note', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_saved_views_owner_principal_id'), ['owner_principal_id'], unique=False)

    op.execute(sa.text("ALTER TABLE plan_shares ADD COLUMN owner_principal_id INTEGER REFERENCES principals(id) ON DELETE RESTRICT"))
    with op.batch_alter_table('plan_shares', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('expires_at', UTCDateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plan_shares_owner_principal_id'), ['owner_principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_shares_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('iterations', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('projects', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))

    with op.batch_alter_table('calendars', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))

    op.execute(sa.text("ALTER TABLE tasks ADD COLUMN executed_by_principal_id INTEGER REFERENCES principals(id) ON DELETE RESTRICT"))
    op.execute(sa.text("ALTER TABLE tasks ADD COLUMN accepted_by_principal_id INTEGER REFERENCES principals(id) ON DELETE RESTRICT"))
    with op.batch_alter_table('tasks', schema=None, naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}) as batch_op:
        batch_op.add_column(sa.Column('is_summary', sa.Boolean(), server_default='0' if op.get_bind().dialect.name == 'sqlite' else 'false', nullable=False))
        batch_op.add_column(sa.Column('baseline_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_revision', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('baseline_provenance', sa.String(length=32), server_default='legacy_unknown', nullable=False))
        batch_op.add_column(sa.Column('started_at', UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('accepted_version', sa.Integer(), nullable=True))

    op.execute(sa.text("UPDATE tasks SET is_summary = true WHERE id IN (SELECT parent_id FROM tasks WHERE parent_id IS NOT NULL)"))
    connection = op.get_bind()
    connection.execute(sa.text("INSERT INTO principals (kind, display_name, enabled, agent_actor_id, created_at) SELECT 'agent', display_name, true, id, :now FROM agent_actors"), {"now": utc_now()})
    views = sa.table('saved_views', sa.column('id', sa.Integer()), sa.column('view_type', sa.String()),
                     sa.column('filters_json', sa.JSON()), sa.column('schema_version', sa.Integer()), sa.column('metric_migration_note', sa.String()))
    cursor = 0
    while True:
        rows = connection.execute(sa.select(views.c.id, views.c.filters_json).where(views.c.id > cursor, views.c.view_type == 'tasks', views.c.schema_version < 2).order_by(views.c.id).limit(100)).all()
        if not rows:
            break
        for view_id, filters in rows:
            filters = dict(filters or {})
            note = None
            if filters.get('isOverdue') is not None:
                filters['isIterationOverflow'] = filters.pop('isOverdue')
                filters['isOverdue'] = None
                note = 'legacy_overdue_means_iteration_overflow'
            connection.execute(views.update().where(views.c.id == view_id).values(filters_json=filters, schema_version=2, metric_migration_note=note))
        cursor = rows[-1][0]


def downgrade():
    raise RuntimeError("Authority, ownership and recovery data require an explicit export/recovery plan before schema retirement")
